# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 7.3
        arguments: build

    - uses: Kir-Antipov/mc-publish@v3.2
      with:
        version-type: alpha
        dependencies: ""
        changelog: ""
        modrinth-featured: false

        modrinth-id: zJpHMkdD
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        curseforge-id: 332273
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        curseforge-files-secondary: ""

        github-token: ${{ secrets.GITHUB_TOKEN }}
